export default [
	{
		name: 'Kim Hyun',
		userImage: 'https://placeimg.com/100/100/arch',
		postImage: 'https://placeimg.com/640/480/arch',
		likes: 36,
		date: 'May 15',
		liked: false,
		content: '#멋진풍경 #눈에담기',
		filter: 'perpetua',
	},
	{
		name: 'John Doe',
		userImage: 'https://placeimg.com/200/200/people',
		postImage: 'https://placeimg.com/640/480/people',
		likes: 20,
		date: 'Apr 20',
		liked: false,
		content: '#오늘 #취미 #일상',
		filter: 'clarendon',
	},
	{
		name: 'Minny',
		userImage: 'https://placeimg.com/100/100/animals',
		postImage: 'https://placeimg.com/640/480/animals',
		likes: 49,
		date: 'Apr 4',
		liked: false,
		content: '내가 사랑하는 내 반려동물',
		filter: 'lofi',
	},
];
